-- Enable the pgvector extension to work with embedding vectors
create extension if not exists vector;

-- ---------------------------------------------------------
-- TABLE: TRADE HISTORY
-- ---------------------------------------------------------
create table if not exists trade_history (
  id bigint generated by default as identity primary key,
  agent_id integer not null,
  market_ticker text not null,
  action text not null, -- 'BUY', 'SELL', 'HOLD'
  price_cents integer,
  quantity integer,
  status text, -- 'PENDING', 'FILLED', 'REJECTED'
  details jsonb, -- Flexible metadata (e.g. reasoning, confidence)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ---------------------------------------------------------
-- TABLE: TRADE ERRORS (Reflexive Memory)
-- ---------------------------------------------------------
create table if not exists trade_errors (
  id bigint generated by default as identity primary key,
  market_ticker text,
  error_type text not null, -- 'TIMEOUT', 'BAD_MATH', 'API_FAIL', 'BAD_CALL'
  description text not null,
  embedding vector(768), -- For RAG retrieval of similar errors (Gemini Text Embedding 004 is 768 dim)
  correction_plan text,
  occurred_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ---------------------------------------------------------
-- INDEXES
-- ---------------------------------------------------------
create index if not exists trade_history_ticker_idx on trade_history (market_ticker);
create index if not exists trade_errors_type_idx on trade_errors (error_type);

-- ---------------------------------------------------------
-- FUNCTION: MATCH ERRORS (RAG)
-- ---------------------------------------------------------
create or replace function match_trade_errors (
  query_embedding vector(768),
  match_threshold float,
  match_count int
)
returns table (
  id bigint,
  description text,
  correction_plan text,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    trade_errors.id,
    trade_errors.description,
    trade_errors.correction_plan,
    1 - (trade_errors.embedding <=> query_embedding) as similarity
  from trade_errors
  where 1 - (trade_errors.embedding <=> query_embedding) > match_threshold
  order by trade_errors.embedding <=> query_embedding
  limit match_count;
end;
$$;
